from __future__ import annotations

import random
import sys
from pathlib import Path
from shutil import copy2

import cv2
import numpy as np
import pandas as pd

# Allow importing use.py from the same folder when this file is run directly.
SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from segment import extract_cell_mask_from_bbox  # noqa: E402


def build_training_masks_sampled_for_test(
    csv_path: str | Path | None = None,
    images_root: str | Path | None = None,
    segmented_root: str | Path | None = None,
    patient_count: int = 10,
    images_per_patient: int = 4,
    seed: int = 42,
) -> int:
    """Test helper for B.

    Randomly selects `patient_count` patients from the training split, then
    samples `images_per_patient` unique images per patient (12 images by default
    when 3 patients × 4 images). For each chosen image, the original image is
    backed up and the mask is generated by `extract_cell_mask_from_bbox` using
    the CSV bbox annotations.

    Output layout:
        /tmp/segment_test/<patient_id>/base-<image_id>
        /tmp/segment_test/<patient_id>/mask-<image_id>
    """

    repo_root = Path(__file__).resolve().parents[3]
    csv_path = Path(csv_path) if csv_path is not None else repo_root / "data" / "raw" / "vindr_detection_folds.csv"
    images_root = Path(images_root) if images_root is not None else repo_root / "data" / "processed" / "images_png"
    segmented_root = Path(segmented_root) if segmented_root is not None else repo_root / "tmp" / "segment_test"

    if patient_count <= 0:
        raise ValueError("patient_count must be > 0")
    if images_per_patient <= 0:
        raise ValueError("images_per_patient must be > 0")

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")
    if not images_root.exists():
        raise FileNotFoundError(f"Images root not found: {images_root}")

    df = pd.read_csv(csv_path, low_memory=False)
    required = {"split", "patient_id", "image_id", "xmin", "ymin", "xmax", "ymax"}
    missing = required.difference(df.columns)
    if missing:
        raise ValueError(f"CSV missing required columns: {sorted(missing)}")

    train_df = df[df["split"].astype(str).str.lower() == "training"].copy()

    train_df = train_df.dropna(subset=["xmin", "ymin", "xmax", "ymax"])
    if "finding_categories" in train_df.columns:
        train_df = train_df[train_df["finding_categories"] != "['No Finding']"]

    if train_df.empty:
        raise ValueError("No training rows found in CSV")

    available_patients = sorted(train_df["patient_id"].dropna().astype(str).unique().tolist())
    if len(available_patients) < patient_count:
        raise ValueError(
            f"Not enough training patients: need {patient_count}, found {len(available_patients)}"
        )

    rng = random.Random(seed)
    selected_patients = rng.sample(available_patients, patient_count)

    out_root = Path(segmented_root)
    out_root.mkdir(parents=True, exist_ok=True)
    print(out_root)
    processed = 0
    for patient_id in selected_patients:
        patient_rows = train_df[train_df["patient_id"].astype(str) == str(patient_id)].copy()
        patient_images = sorted(patient_rows["image_id"].dropna().astype(str).unique().tolist())
        if not patient_images:
            continue

        selected_images = rng.sample(patient_images, k=min(images_per_patient, len(patient_images)))

        for image_id in selected_images:
            image_group = patient_rows[patient_rows["image_id"].astype(str) == str(image_id)].copy()
            image_path = images_root / str(patient_id) / str(image_id)
            if not image_path.exists():
                alt = images_root / str(patient_id) / Path(str(image_id)).name
                if alt.exists():
                    image_path = alt
                else:
                    alt_png = images_root / str(patient_id) / f"{Path(str(image_id)).stem}.png"
                    if alt_png.exists():
                        image_path = alt_png
                    else:
                        continue

            raw = np.fromfile(str(image_path), dtype=np.uint8)
            img = cv2.imdecode(raw, cv2.IMREAD_UNCHANGED)
            if img is None:
                continue

            patient_dir = out_root / str(patient_id)
            patient_dir.mkdir(parents=True, exist_ok=True)
            base_out_path = patient_dir / f"base-{Path(str(image_id)).name}"
            mask_out_path = patient_dir / f"mask-{Path(str(image_id)).name}"

            try:
                copy2(image_path, base_out_path)
            except Exception:
                encoded = cv2.imencode(Path(str(image_id)).suffix or ".png", img)[1]
                encoded.tofile(str(base_out_path))

            union_mask = np.zeros(img.shape[:2], dtype=np.uint8)
            valid_rows = image_group[["xmin", "ymin", "xmax", "ymax"]].dropna()
            for _, row in valid_rows.iterrows():
                one_mask = extract_cell_mask_from_bbox(
                    img,
                    float(row["xmin"]),
                    float(row["ymin"]),
                    float(row["xmax"]),
                    float(row["ymax"]),
                )
                union_mask = cv2.bitwise_or(union_mask, one_mask)

            ok, buf = cv2.imencode(".png", union_mask)
            if not ok:
                continue
            buf.tofile(str(mask_out_path))
            processed += 1

    return processed


if __name__ == "__main__":
    build_training_masks_sampled_for_test()
